# =============================================================================
# MSS project: figures and tables
# File: code/06_figures_and_tables.R
#
# Purpose:
#   - Generate manuscript-style figures and supplementary plots
#   - Visualize main Cox regression results
#   - Plot correlation heatmaps
#   - Plot discordance analysis results
#   - Plot mediation summary if available
#
# Required inputs (generated by previous scripts):
#   - output/tables/cox_results_mss_continuous.csv
#   - output/tables/sensitivity_additional_sleep_metrics.csv (optional)
#   - output/tables/mrs_shap_feature_importance.csv (optional)
#   - output/tables/mrs_mss_correlation.csv (optional)
#   - output/tables/sensitivity_discordance_results.csv (optional)
#   - output/tables/mrs_mediation_summary.csv (optional)
#   - data/derived/final_imp.csv
#   - data/derived/final_mrs.csv (optional)
# =============================================================================

source("code/00_setup.R")

dir.create(dir_figures, recursive = TRUE, showWarnings = FALSE)

# ---- 1. Load analysis-ready data ---------------------------------------------

file_final_imp <- file.path(dir_derived, "final_imp.csv")
final_imp <- if (file.exists(file_final_imp)) safe_read_csv(file_final_imp) else NULL

file_final_mrs <- file.path(dir_derived, "final_mrs.csv")
final_mrs <- if (file.exists(file_final_mrs)) safe_read_csv(file_final_mrs) else NULL

# ---- 2. File paths for derived results ---------------------------------------

file_mss_cont <- file.path(dir_tables, "cox_results_mss_continuous.csv")
file_additional_sleep <- file.path(dir_tables, "sensitivity_additional_sleep_metrics.csv")
file_discordance <- file.path(dir_tables, "sensitivity_discordance_results.csv")
file_mediation <- file.path(dir_tables, "mrs_mediation_summary.csv")

# ---- 3. Disease labels -------------------------------------------------------

disease_mapping <- c(
  t2d = "Type 2 diabetes",
  obese = "Obesity",
  hp = "Hypertension",
  lipid = "Dyslipidemia",
  ihd = "Ischemic heart diseases",
  af = "Atrial fibrillation",
  conduction = "Conduction disorder",
  hf = "Heart failure",
  is = "Ischemic stroke",
  dementia_ad = "Dementia",
  depressive = "Depression",
  anxiety = "Anxiety",
  cancer = "Cancer",
  death = "All-cause mortality"
)

# ---- 4. Helper to parse HR (CI) strings -------------------------------------

parse_hr_ci <- function(df, hr_col = "HR_95CI") {
  if (!hr_col %in% names(df)) return(df)
  
  out <- df %>%
    mutate(
      HR = as.numeric(sub(" .*", "", .data[[hr_col]])),
      CI_temp = gsub(".*\\(|\\)", "", .data[[hr_col]]),
      CI_Lower = as.numeric(sapply(strsplit(CI_temp, "-"), `[`, 1)),
      CI_Upper = as.numeric(sapply(strsplit(CI_temp, "-"), `[`, 2))
    )
  
  out
}

# ---- 5. Figure 1-style heatmap: main MSS results -----------------------------

if (file.exists(file_mss_cont) && file.exists(file_additional_sleep)) {
  main_results <- safe_read_csv(file_mss_cont)
  additional_results <- safe_read_csv(file_additional_sleep)
  
  # combine MSS main score and additional sleep dimensions
  heatmap_df <- bind_rows(
    additional_results %>%
      mutate(Predictor_Type = "Sleep dimension"),
    main_results %>%
      filter(Predictor %in% c("mss", "mss_std")) %>%
      mutate(Predictor_Type = "Summary score")
  )
  
  heatmap_df <- parse_hr_ci(heatmap_df, hr_col = "HR_95CI") %>%
    mutate(
      Disease = disease_mapping[Disease],
      Predictor = case_when(
        Predictor == "insomnia" ~ "Insomnia",
        Predictor == "doze" ~ "Daytime sleepiness",
        Predictor == "snore" ~ "Snoring",
        Predictor == "daytime_nap" ~ "Daytime nap",
        Predictor == "regularity" ~ "Regularity",
        Predictor == "epijetlag" ~ "Epi-jetlag",
        Predictor == "preference" ~ "Chronotype preference",
        Predictor == "socialjetlag" ~ "Social jetlag",
        Predictor == "onset" ~ "Sleep onset",
        Predictor == "efficiency" ~ "Sleep efficiency",
        Predictor == "duration" ~ "Accelerometer sleep duration",
        Predictor == "duration_report" ~ "Self-reported sleep duration",
        Predictor == "mss" ~ "MSS",
        Predictor == "mss_std" ~ "MSS (per SD)",
        TRUE ~ Predictor
      ),
      P_num = as.numeric(ifelse(P_Value == "<0.001", 0.0005, P_Value)),
      Signif = case_when(
        P_num < 0.001 ~ "***",
        P_num < 0.01 ~ "**",
        P_num < 0.05 ~ "*",
        TRUE ~ ""
      ),
      Disease_Group = case_when(
        tolower(Disease) %in% c("type 2 diabetes", "obesity", "hypertension", "dyslipidemia") ~ "Metabolic",
        tolower(Disease) %in% c("ischemic stroke", "heart failure", "ischemic heart diseases",
                                "atrial fibrillation", "conduction disorder") ~ "Cardiovascular",
        tolower(Disease) %in% c("dementia", "depression", "anxiety") ~ "Neurological",
        TRUE ~ "Other"
      )
    )
  
  p_heatmap_main <- ggplot(heatmap_df, aes(x = Predictor, y = Disease, fill = HR)) +
    geom_tile(color = "white", linewidth = 0.4) +
    geom_text(aes(label = Signif), size = 3, color = "black", na.rm = TRUE) +
    scale_fill_gradient2(
      low = "#3B9AB2",
      mid = "#EEEEEE",
      high = "#F21A00",
      midpoint = 1.0,
      name = "HR"
    ) +
    facet_wrap(~ Disease_Group, scales = "free_y") +
    theme_minimal(base_size = 11) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.grid = element_blank(),
      strip.text = element_text(face = "bold")
    ) +
    labs(x = "Sleep measure", y = "Outcome")
  
  ggsave(
    filename = file.path(dir_figures, "figure1_sleep_outcome_heatmap.tiff"),
    plot = p_heatmap_main,
    width = 12,
    height = 7,
    dpi = 600,
    compression = "lzw"
  )
}

# ---- 6. Correlation heatmap among sleep variables ----------------------------

if (!is.null(final_imp)) {
  sleep_corr_vars <- intersect(
    c(
      "insomnia", "doze", "snore", "regularity", "epijetlag", "socialjetlag",
      "onset", "efficiency", "daytime_nap", "duration", "duration_report",
      "mss", "hss"
    ),
    names(final_imp)
  )
  
  if (length(sleep_corr_vars) >= 3 &&
      requireNamespace("Hmisc", quietly = TRUE) &&
      requireNamespace("ComplexHeatmap", quietly = TRUE) &&
      requireNamespace("circlize", quietly = TRUE)) {
    
    corr_data <- final_imp[, sleep_corr_vars, drop = FALSE]
    corr_res <- Hmisc::rcorr(as.matrix(corr_data), type = "spearman")
    
    corr_mat <- corr_res$r
    p_mat <- corr_res$P
    
    star_mat <- matrix("", nrow = nrow(corr_mat), ncol = ncol(corr_mat))
    star_mat[p_mat < 0.001] <- "***"
    star_mat[p_mat < 0.01 & p_mat >= 0.001] <- "**"
    star_mat[p_mat < 0.05 & p_mat >= 0.01] <- "*"
    
    rownames(star_mat) <- rownames(corr_mat)
    colnames(star_mat) <- colnames(corr_mat)
    
    corr_display <- corr_mat
    corr_display[upper.tri(corr_display)] <- NA
    
    col_fun <- circlize::colorRamp2(c(-1, 0, 1), c("#3B9AB2", "#EEEEEE", "#F21A00"))
    
    tiff(
      filename = file.path(dir_figures, "supplementary_sleep_correlation_heatmap.tiff"),
      width = 8, height = 7, units = "in", res = 600, bg = "white"
    )
    
    ht <- ComplexHeatmap::Heatmap(
      corr_display,
      name = "Spearman\ncorrelation",
      col = col_fun,
      na_col = "white",
      cluster_rows = FALSE,
      cluster_columns = FALSE,
      rect_gp = grid::gpar(col = "white", lwd = 1),
      row_names_gp = grid::gpar(fontsize = 10),
      column_names_gp = grid::gpar(fontsize = 10),
      column_names_rot = 45,
      cell_fun = function(j, i, x, y, width, height, fill) {
        if (i >= j) {
          grid::grid.text(star_mat[i, j], x, y, gp = grid::gpar(fontsize = 9))
        }
      }
    )
    
    ComplexHeatmap::draw(ht, heatmap_legend_side = "left")
    dev.off()
  }
}

# ---- 7. MRS–sleep correlation heatmap ---------------------------------------

if (!is.null(final_mrs)) {
  metabolite_vars <- intersect(c("CYC", "Triglycerides", "HDL", "ALT", "CRP", "MRS"), names(final_mrs))
  sleep_vars <- intersect(
    c("insomnia", "doze", "snore", "epijetlag", "regularity",
      "socialjetlag", "onset", "efficiency", "daytime_nap", "duration", "mss"),
    names(final_mrs)
  )
  
  if (length(metabolite_vars) >= 2 && length(sleep_vars) >= 2) {
    corr_grid <- expand.grid(
      Predictor = metabolite_vars,
      Outcome = sleep_vars,
      stringsAsFactors = FALSE
    ) %>%
      rowwise() %>%
      mutate(
        Correlation = tryCatch(
          cor.test(final_mrs[[Predictor]], final_mrs[[Outcome]], method = "spearman", exact = FALSE)$estimate,
          error = function(e) NA_real_
        ),
        P_value = tryCatch(
          cor.test(final_mrs[[Predictor]], final_mrs[[Outcome]], method = "spearman", exact = FALSE)$p.value,
          error = function(e) NA_real_
        )
      ) %>%
      ungroup() %>%
      mutate(
        P_adj = p.adjust(P_value, method = "fdr"),
        Signif = case_when(
          P_adj < 0.001 ~ "***",
          P_adj < 0.01 ~ "**",
          P_adj < 0.05 ~ "*",
          TRUE ~ ""
        )
      )
    
    p_corr <- ggplot(corr_grid, aes(x = Predictor, y = Outcome, fill = Correlation)) +
      geom_tile(color = "white") +
      geom_text(aes(label = Signif), size = 3) +
      scale_fill_gradient2(
        low = "#3B9AB2",
        mid = "#EEEEEE",
        high = "#F21A00",
        midpoint = 0,
        name = "rho"
      ) +
      theme_minimal(base_size = 11) +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid = element_blank()
      ) +
      labs(x = "Biomarker / MRS", y = "Sleep measure")
    
    ggsave(
      filename = file.path(dir_figures, "supplementary_mrs_sleep_correlation_heatmap.tiff"),
      plot = p_corr,
      width = 7,
      height = 6,
      dpi = 600,
      compression = "lzw"
    )
  }
}

# ---- 8. Discordance forest plot ---------------------------------------------

if (file.exists(file_discordance)) {
  discordance_df <- safe_read_csv(file_discordance) %>%
    parse_hr_ci(hr_col = "Level1_HR_95CI") %>%
    mutate(
      Disease = factor(
        disease_mapping[Disease],
        levels = disease_mapping
      ),
      Predictor = case_when(
        Predictor == "dur_consistent" ~ "Subjective vs objective duration",
        Predictor == "ins_consistent" ~ "Insomnia vs sleep onset",
        Predictor == "doze_consistent" ~ "Sleepiness vs nap",
        Predictor == "mss_hss_consistent_z" ~ "MSS vs HSS consistency",
        Predictor == "obj_sub_consistent_z" ~ "Objective vs subjective MSS",
        TRUE ~ Predictor
      ),
      P_num = as.numeric(ifelse(Level1_P == "<0.001", 0.0005, Level1_P)),
      Signif = case_when(
        P_num < 0.001 ~ "***",
        P_num < 0.01 ~ "**",
        P_num < 0.05 ~ "*",
        TRUE ~ ""
      ),
      star_x = CI_Upper * 1.05
    )
  
  p_discordance <- ggplot(discordance_df, aes(x = HR, y = Predictor, xmin = CI_Lower, xmax = CI_Upper)) +
    geom_vline(xintercept = 1, linetype = "dashed", color = "grey50") +
    geom_point(size = 2.2, color = "black") +
    geom_errorbarh(height = 0.2, color = "black") +
    geom_text(aes(x = star_x, label = Signif), hjust = 0, size = 4) +
    scale_x_continuous(trans = "log10") +
    facet_wrap(~ Disease, scales = "free_y", ncol = 3) +
    theme_bw(base_size = 11) +
    theme(
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(face = "bold"),
      panel.grid.minor = element_blank()
    ) +
    labs(x = "Hazard ratio (95% CI)", y = NULL)
  
  ggsave(
    filename = file.path(dir_figures, "supplementary_discordance_forest_plot.tiff"),
    plot = p_discordance,
    width = 14,
    height = 10,
    dpi = 600,
    compression = "lzw"
  )
}

# ---- 9. Mediation forest plot ------------------------------------------------

if (file.exists(file_mediation)) {
  mediation_df <- safe_read_csv(file_mediation)
  
  if (all(c("Disease", "pm") %in% names(mediation_df))) {
    mediation_plot_df <- mediation_df %>%
      mutate(
        Disease_Label = disease_mapping[Disease],
        pm_pct = pm * 100
      ) %>%
      filter(!is.na(pm_pct), !is.na(Disease_Label))
    
    p_mediation <- ggplot(mediation_plot_df, aes(x = pm_pct, y = reorder(Disease_Label, pm_pct))) +
      geom_point(size = 2.5, color = "#2b8cbe") +
      geom_vline(xintercept = 0, linetype = "dashed", color = "grey50") +
      theme_bw(base_size = 11) +
      theme(
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank()
      ) +
      labs(
        x = "Proportion mediated (%)",
        y = NULL,
        title = "Estimated mediation by MRS"
      )
    
    ggsave(
      filename = file.path(dir_figures, "supplementary_mediation_forest_plot.tiff"),
      plot = p_mediation,
      width = 6,
      height = 8,
      dpi = 600,
      compression = "lzw"
    )
  }
}

message("Figure generation complete.")